name: Clone
on:
  #Run every 12 hours
  schedule:
    - cron: "30 8 * * *"
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run action
        uses: andrewthetechie/gha-clone-releases@v1.7.0
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          src_repo: DragonStorm25/hook-game
          dest_repo: DragonStorm25/hook-game-releases
          copy_assets: true
